### ISSUE TITLE
No cache-busting for `lime-elements.esm.js`

### ISSUE THREAD

**Issue by jensgustafsson** [Lundalogik/lime-elements#1000]
# No cache-busting for `lime-elements.esm.js`

## Current behavior

When upgrading to a new version of lime-elements, we run the risk of not getting the latest changes as an old version of lime-elments  might be cached in the browser.

## Expected behavior

Always fetch the latest version from the server

## Proposal:

Set `hashFileNames` to true in `stencil.conf.ts`. I haven't tested it yet but that's what you should do accoring do the docs:

> During production builds, the content of each generated file is hashed
> to represent the content, and the hashed value is used as the filename.
> If the content isn't updated between builds, then it receives the same
> filename. When the content is updated, then the filename is different.
>
> By doing this, deployed apps can "forever-cache" the build directory and
> take full advantage of content delivery networks (CDNs) and heavily
> caching files for faster apps.

## More info

* How cache busting works: https://www.codebyamir.com/blog/a-web-developers-guide-to-browser-caching
* Stencil docs: https://stenciljs.com/docs/config

**Comment by adrianschmidt** [comment]
Hashing of filenames is already done correctly. `lime-elements.esm.js` is the entry-file, and cannot be hashed, because then the frontend wouldn't know what file to load. So that file has to either be served with correct cache headers, or requested with a cache-busting query-string. The former option is, as far as I know, regarded as the better one.

Since there's no bug in lime-elements, I'm closing this issue.
