### ISSUE TITLE
Lime elements fails to initialize in non-Chromium Edge

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#1033]
## Current behavior

Lime elements fails to initialize in Edge. 

## Environment

- **lime-elements** version: 29.6.2
- Framework used: Vanilla.js
- Browser: Microsoft Edge 44.19041.423.0

**Comment by adrianschmidt** [comment]
This is almost certainly because we updated to Stencil 2 a while back, and did not enable building of legacy js-formats, which was disabled by default in Stencil 2. We need to enable that again.

**Comment by adrianschmidt** [comment]
Technically, there are two ways we can choose between:

1. Enable "legacy" build-output. This *should* just be a matter of changing two booleans in the build-config, and we obviously need to test that it worked as well. So it's a *little* work, but if it works as expected, it shouldn't be much.

2. Decide that lime-elements has the same very strict browser requirement that Lime CRM Web Client has, which means Lime Go also has to restrict their browser requirement. It also means that any outward facing site, like the eSign portal (which have to support a wider range of browsers because not all users are customers), will be unable to use lime-elements, or will have to manage using lime-elements for compatible browsers, and provide other solutions for non-compatible browsers.

I *strongly* consider option 2 to be the *wrong* way to go for lime-elements, but as we've agreed that new issues should go through triage, I'm laying out the options here 🙂

Ping @magnusfagerlund

**Comment by JohannesHansen** [comment]
Note that this issue currently prevents Lime Go from using Lime Elements 29 and above.

**Comment by magnusfagerlund** [comment]
Lets go with option 1. Maybe something for cool-down?
