### ISSUE TITLE
Create a component for mini widgets, which can be used by add-ons 

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1096]
## New feature motivation
Add-ons use specific components which look like a simple button, but they have their own complexities. For example, they sometimes show double lines of text with slightly different styles. They may show a progress spinner, etc... Using a `limel-button` is not enough for their use case.
In this issue: https://github.com/Lundalogik/limepkg-esign/issues/548#issuecomment-737743693 we have touched upon this problem, and have had some separate discussions with @justFredster, @BregenzerK, @adrianschmidt, @FredrikWallstrom and @eketorp.

The solution in add-ons for now is having code that is duplicated for each and every add-on. It makes it very hard to maintain, creating an unsustainable workflow.

## New feature description
We ultimately and preferably need to have reusable component that all of these add-ons can use. All such add-ons will then look the same and work the same way. And we will be in control of their universal design.

## New feature implementation
In my head, Lime Elements is a component library where we offer the basic components such as buttons, sliders, menus, etc... Basically, building blocks of larger and more complex components.

However we ourselves put together a few of these components to create more complex components for our use in the CRM. For instance things that we have in `crm-components` repo (views, action bar, etc..). 

It'd be awesome to have a component library for them as well, so others can reuse them too. We could call it Lime Molecules 😄 It can be a separate place, or a section within Lime Elements. 

Then we could even put other web-components such as info-tiles, or these add-on stuff in that component library.

This would of course need some more work for documentation and such. But makes us more sustainable in the long run.

**Comment by adrianschmidt** [comment]
Just adding some of my thoughts:

> In my head, Lime Elements is a component library where we offer the basic components such as buttons, sliders, menus, etc... Basically, building blocks of larger and more complex components.
> 
> However we ourselves put together a few of these components to create more complex components for our use in the CRM. For instance things that we have in `crm-components` repo (views, action bar, etc..).

`lime-crm-components` are specifically for use in the Lime CRM web client. The deciding factor for if a component belongs there isn't its size or complexity, but whether it's specific to the Lime CRM web client. Components in lime-elements need to be generic, and shouldn't "know" specifics about the client they are used in, while components in lime-crm-components are considered "internal" to lime-webclient. In fact, the major reason for the division into two separate repos is the difference in the technology used: StencilJS vs Angular.

Any add-on that runs in the Lime CRM web client could technically use any component from lime-crm-components, but the components are not documented in a way that is meant for, and accessible by, people outside our dev-department. We might want to add such documentation at some point, but we might also not want that, since opening up a package for use by others also means that we need to be more careful about making breaking changes in it. Frankly, I envision a future where most, if not all, of the Angular code in lime-webclient has been replaced by web components built in lime-crm-components, making lime-crm-components more or less replace lime-webclient. (I'm talking about the _repos_, the _application_ the users see would still be the Lime CRM web client, of course.)

> It'd be awesome to have a component library for them as well, so others can reuse them too. We could call it Lime Molecules 😄 It can be a separate place, or a section within Lime Elements.

Yes, we may want to have some "higher level" and/or more complex components in a public component package. Whether we build them in a new separate package, or inside lime-elements, I don't know. I guess I can see one or two arguments for either side. I haven't formed any strong opinion on that specific matter yet.

Aside: "Lime Molecules" confused me for a second, and then made me smile 😊. I just named Lime Elements from the fact that html components are called "elements", and Lime Elements is kind of meant to supply "improved" html elements… and yeah, that in itself kind of feels like an argument for putting bigger, or "higher level", components in a separate package…

> Then we could even put other web-components such as info-tiles, or these add-on stuff in that component library.

Since info-tiles is an add-on, it's basically a product-inside-the-product… I think someone will object if we put that component in a public library… 😅

**Comment by Kiarokh** [comment]
I agree. Publicly available "molecules" which are made for CRM are really bad idea. 😄 but having a place to maintain these reusable web-components internally (we [feature, add-ons, etc..] + consultants) would be great.

For the info-tiles example, I can imagine that we would fit in the new overview tabs in object cards. It'd be nice if they are also reusable so that folks can create custom "info-tiles" inside object. (Which don't have to open a global table, but instead can open a filtered selection of data inside an object)

**Comment by eketorp** [comment]
I think this is a great idea. But first, I want to understand:
A. How urgent is this? 
B. Do we have some great stuff "in the basement" that we have no "shelves" for? Can we start this "Molecule Store" with some stuff to display?

I want to make sure that we have great stuff to put there before creating the "app store", if you understand my point. Wouldn't you agree that the "ooumph" would be greater if we had a couple of great molecules from day one?

Would it make more sense to let the redesign "settle" first and let people start building this that fit into it? From a work order perspective, enabling the "new object card" (hopefully including space to put buttons next to action menu) is the enabler to _start_ building molecules.

**Comment by Kiarokh** [comment]
Good question Tomas

My technical knowledge is way too little to have a good answer regarding the cost versus profit of having a store. And I cannot therefore argue about whether this can be motivated with the resources and limitations that we have today or not. 

But I just know the need of having these things organized in one place exists. I know for instance that the history-feed web-component that we have in the crm-components repo was somehow reused by @SimonJehrbo 's team to create a a timeline view for support tickets. But if I'm not mistaken, the usage was not like what we normally do in Lime Elements. If we update a component offered in Lime Elements, everyone using it can get an update and use all the new improvements. But Helpdesk will never get any updates from changes in the activity feed component. Because they just copy/pasted our solution. They have to keep an eye on our changes and manually update their code. (plz correct me if I', wrong). Same goes for the action bar component, etc…

In case of add-ons, there are already several add-ons having the same structure. Code is just duplicated in each and every add-on to render the UI. It would have been much easier to have the same 
source of truth for them. Which is also why @BregenzerK asked me to make an issue for it here.

Having an App Store (another private lime elements thingy) or not? I can't answer the question. I guess it's mostly a matter of having a discipline of developing things like these for reusability, and having a common place to host the source code. How it is done I don't know.

**Comment by adrianschmidt** [comment]
I don't think we've been talking about an app store for the add-ons… at least I haven't. Unless I've misunderstood something, what we're talking about here is lower level than complete add-ons: common reusable components that can be used both by the web client core, and by add-ons, and possibly by other clients and products as well, like Lime Go. Basically, the same thing as what Lime Elements is already providing, but for more complex components.

**Comment by justFredster** [comment]
@adrianschmidt  Yes, you are right, this is not for complete add-ons. :) I think @eketorp just used the term "app store" as a reference to explain how he meant. (I hope that at least... ;) ).

**Comment by eketorp** [comment]
You're absolutely right, Fredrik.
