### ISSUE TITLE
Make input components somewhat consistent regarding `disabled` and `readonly`

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1195]
## New feature motivation

Currently, some input components differentiates between `disabled` and `readonly`. For example `limel-picker`:

Enabled:
![image](https://user-images.githubusercontent.com/154725/112631889-c090e980-8e37-11eb-83da-4a91790dff47.png)

Readonly:
![image](https://user-images.githubusercontent.com/154725/112631911-c7b7f780-8e37-11eb-914d-88b93b148055.png)

Disabled:
![image](https://user-images.githubusercontent.com/154725/112631989-d9999a80-8e37-11eb-99f4-27e716c1f245.png)

In other words, when the component is `readonly`, the value cannot be changed, but can still be interacted with in other ways. When `disabled`, all interactions are disabled.

The problem is that we can't really use that in the Lime web client, because some other input components that have no need for the differentiation only have the `disabled` property.

That means that a consumer that wishes to prevent the user from changing the value of a component either has to check which component is being used, and know if that component supports `readonly`, or it has to just blanket use `disabled`, which is less than ideal.

## New feature description

It would be nice if all input components had both `readonly` and `disabled`. For components where the difference doesn't matter, setting either property to `true` should make the component readonly (or disabled, whichever you prefer to call it). That way, a consumer without intimate knowledge of the components can still prevent values to be changed, while still allowing "other" interactions, should the component happen to have any.

## New feature implementation

All components that only support either `readonly` or `disabled`, but not both, should support both. As a first step, the new property can just work exactly the same as the one already implemented. As a further step, any components that may benefit from differentiating between the two, but doesn't already, could be updated to behave differently between the two states.

**Comment by Kiarokh** [comment]
This is an interesting subject and triggers some thoughts in my head. 

Things that are `disabled` are in other words potentially "interact-able". It usually means that if some conditions are (or would be) met, then they could become interactive again and let the users change their values or manipulate them. What I am trying to say is that the disabled state conveys this message that the element is disabled for a reason (and hopefully the user knows the reason too).

However, readonly is a totally different thing. An element that is readonly does not at all need to look like an "otherwise-interactable-element". It doesn't need to visualize any affordance for changeability or for receiving or accepting user input. Readonly could be even called Informative-only or illustrative-only. 

Perhaps the best example is a `textarea` which can be rendered as a half-transparent and greyed-out text box –completed with a `cursor: not-allowed` style— when `disabled`. But when `readonly` it could be visualized as a nice paragraph or block of text with no opacity and fully readable, or individually scrollable if suitable.

There is for instance no point in showing the Bisnode information fileds in the Company overview tab as `disabled`. Because users cannot tweak them under any circumstances anyways. They get their data from elsewhere. It's better to visualize them as informative pieces of texts instead (no text-boxes around them with grayed-out outlines, which indicate that there is a slight chance that users can edit them some day or under certain circumstances).

There is no need to show a slider with that elevated and draggable knob, when it's just trying to visualize a percentage that users cannot change. Same goes for toggle buttons, check boxes, and so forth.

This will become extra important when we get the view-mode/edit-mode as well.

**Comment by Kiarokh** [comment]
I think we can play a lot with visual styles of many of these components in `readonly` mode, once this is merged.
