### ISSUE TITLE
limel-list: how can we improve support for longer texts in narrow lists, like on phones?

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1221]
Spawned from [this forum thread](https://forum.lime-crm.com/t/css-on-limel-list-lime-elements/3618) by @viktorSoftDev

> The use case is working on mobile. A set-field or option list with long option names overflow the standard component on the card and the customer does not want to rename them, but also se the whole name.

Some screenshots:
![limel-list in dialog](https://user-images.githubusercontent.com/154725/115210159-a082dc00-a0fe-11eb-8533-02a81401659d.png)
![limel-select](https://user-images.githubusercontent.com/154725/115210165-a1b40900-a0fe-11eb-889a-cc96c5978499.png)

There's an issue for making the `secondaryText` property wrap to multiple lines, but should it also be possible to have the `text` property wrap? Or have some other way to see the whole text if it's truncated? Tooltip on hover won't work since the problem is chiefly present on mobile.

**Comment by adrianschmidt** [comment]
And obviously: do we need to improve it here, or is it something the consultant should build their own component for?

**Comment by Kiarokh** [comment]
Yes, I think we should certainly add support for it in lime-elements

**Comment by adrianschmidt** [comment]
I don't think this is "ready for dev", because we don't even have a proposed solution for it?

**Comment by Kiarokh** [comment]
I think we can do something like what we just did here: https://github.com/Lundalogik/crm-feature/issues/1212 
I'll have to investigate a bit. But should be fairly similar

**Comment by anderssonjohan** [comment]
Much of the data in your examples, such as an product/article picker, another solution is to support "ellipsis in the middle of a sentence". An example with names:

```
Johan Anderss...
Johan Anderss...
Johan Anderss...
```

..with ellipsis in the center:

```
Johan...on (Dev)
Joha...n (Sales)
Johan...son (PM)
```

But this "mac style" of ellipsis only works using two elements for now.. which looks really ugly when the second part gets cut off in the middle of a character. (https://codepen.io/markchitty/pen/RNZbRE)

Multiline items in lists/tables are a bit wacky, but it depends. It's allowed in spreadsheets but it won't make a nice table. :) 
I would recommend using "tap to read more" in every case using a list on mobile. Imagine if your spotify client included the lyrics in the list items... 👀 And when I say tap to read more I would go 1) use a dialog/view with back button support 2) if I must, use some kind of expander to open/close the list item to read all of the content.

For article data like the one in the screenshot I would go for tokenizing into several properties and use the secondary text for important stuff. Most of this kind of data is just concatenated into a descriptive from other properties anyways, so..

**Comment by Kiarokh** [comment]
@viktorSoftDev I'd like to close this issue because:
- It has been a long time and I think you have found other workarounds for it, since we haven't heard more from you.
- I think there is already a good workaround for it as Adrian mentions, which is using the secondaryText. (Note: we have a [small visual issue](https://github.com/Lundalogik/crm-feature/issues/2573) for now, but I'll fix that separately).
- also this one https://github.com/Lundalogik/crm-feature/issues/2572 gives your list items a few more characters

You can check out the workaround here: https://lundalogik.github.io/lime-elements/versions/next/#/component/limel-list/

![image](https://user-images.githubusercontent.com/35954987/147573999-03ffd221-9dd5-4992-bb6a-318d63149ad3.png)

Let me know if this doesn't work for your use case at all and you are still waiting for a solution, so we look into it again.

@anderssonjohan your suggested solution would be nice instead of a direct truncation, but since it's JS I don't dare adding it to Elements. Anyhow, such a solution is not without complications neither. For instance, in our context (Lime Elements), thi should be an optional feature to activate; and we probably want to let the consumer choose how many characters they'd like to show at the ending, for certain container widths.
