### ISSUE TITLE
Add `gap` as a prop to `limel-flex-container` (WIP)

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1251]
## New feature motivation

The `gap` is a super nifty feature which was only available for `grid`. But they have recently added it to `flex` as well, and there is a [good browser support](https://caniuse.com/flexbox-gap) for it.

Having this will enable consumers to easily add space between flexbox items, without writing CSS.

you can see sometimes it's a bit hard to scan the UI, when elements such as checkboxes or toggles are placed in `<limel-flex-container>` like:
![image](https://user-images.githubusercontent.com/35954987/119151852-0e009000-ba50-11eb-96e1-98a85dec5821.png)
or
![image](https://user-images.githubusercontent.com/35954987/119151923-1eb10600-ba50-11eb-83d8-c1047ad96423.png)
Because they are rendered too close to each other.

But with a gap, they could look like this:
![image](https://user-images.githubusercontent.com/35954987/119152176-5a4bd000-ba50-11eb-920f-530fc9fcae80.png)

![image](https://user-images.githubusercontent.com/35954987/119152135-515afe80-ba50-11eb-8675-57bead1f860d.png)

## New feature implementation

I have an idea about how to do it, but cannot write the code for it myself. The CSS-part of the solution is in the PR. The idea is that the consumer just types a number for their `gap` property, and the CSS converts it to a `rem` value.

We need to render an inline style in the DOM, something like this: 
````html
<limel-flex-container style="--flex-container-gap: {gap}">
````

and since the css is like below, things will be working fine:
````
:host(limel-flex-container) {
    display: flex;
    gap: calc(var(--flex-container-gap, 0) * 1rem);
}
````

checkout the branch and add the inline style to see it already works :)

**Comment by Kiarokh** [comment]
when the feature is done, we can add it to a bunch of examples in the docs as well :) 

what do think @adrianschmidt

**Comment by adrianschmidt** [comment]
I think the limel-flex-container is a weird component, that doesn't really have much reason to exist. It started out as a container specifically for putting buttons in, and wasn't meant to be super-configurable, but rather be a quick way to put two or three buttons on the same line, and have them appear nicely with correct spacing and stuff.

At some point, I let myself be convinced that "it's really just a flex-container, and anything can be but in it, so it shouldn't be called `limel-button-container`" (or whatever it was called back then), and so it was renamed. But now it's really just a reimplementation of css flexbox, partially configurable with html attributes instead of css. I think we should consider deprecating it instead.

Thoughts @jgroth?

**Comment by Kiarokh** [comment]
Well.... it's correct. It feels one could just write the CSS directly, instead of using that. However, I've seen this being used in many place, both in our code and in add-ons and so forth. For some reason, developers seem to like it. Maybe because most of them don like writing CSS(?)

Anyhow, if you're gonna remove it, I'm cool. But if it's gonna stay, it' be nice to offer the `gap` as well. For the "composite" examples in lime elements at least, it's nice when we don't have to import a SCSS file, just to align the toggles or checkboxes. But even that's not a big deal.

**Comment by jgroth** [comment]
Yeah I agree that it's a bit of a weird component since it's just a wrapper for CSS grid. I never like to use it myself since I find it easier to just write the CSS instead, but maybe others who don't know much about CSS find it more useful?

It might also be that we see it in use so much because it's used in some of our examples, and people tend to love copy and pasting code :smile: 

Same arguments can be made for the grid component, since that is also just a wrapper for the CSS grid

**Comment by adrianschmidt** [comment]
I'm going to deprecate the flex-container component, so I'll close this.
