### ISSUE TITLE
Datetime picker: Time input doesn't change when updating time programmatically

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#1310]
## Current behavior

When changing the time programatically the time input doesn't reflect the change. (See image below)
![image](https://user-images.githubusercontent.com/3470434/127638994-49d6433c-3f29-4d29-9ee2-b48cd3b6cc8d.png)

1. In the docs, go to the example "Changing the input programmatically" in Datepicker
2. Open the calendar dropdown
3. Add a few hours with the "Add hour"-button
4. Open the calendar dropdwn again; the time input will not reflect the current time

This issue is present both in the datetime picker and in the time picker.

## Expected behavior

The current value should be correctly reflected in the time input

## Environment

- **lime-elements** version: 33.1.0
- Framework used: Stencil.js, React

**Comment by blombergedvin** [comment]
Could this issue be related to flatpickr not accepting input @adrianschmidt ?
Related conversation on slack @JohannesHansen  https://lime-technologies.slack.com/archives/C1K6TN9BK/p1630316799065000

**Comment by adrianschmidt** [comment]
> Could this issue be related to flatpickr not accepting input @adrianschmidt ?

In a way, yes. We disabled direct input because the flatpickr widget didn't update when the user changed the value directly in the input field. If the widget updated, letting the user input the value directly wouldn't be a problem. And the bug reported here is actually very similar to that…

I'd say that if we solve one, it's pretty likely that solves the other one too…

**Comment by LucyChyzhova** [comment]
Just tested and it works as wanted:



https://github.com/user-attachments/assets/31d052b7-a564-436d-8796-92f803cfbab4
