### ISSUE TITLE
Tooltip content is positioned in relation to `limel-tooltip` instead of the trigger element

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1408]
## Current behavior
![Screenshot 2022-08-04 at 12 35 39](https://user-images.githubusercontent.com/35954987/182827360-182df61f-257e-4969-9fb2-e0ee2e49043c.png)

The popover with the tooltip content is positioned in relation to the `<div class="trigger-anchor">` inside the `<limel-tooltip />`  instead of in relation to the trigger element. That's a problem if those elements are not rendered right next to each other, as may be the case when the target element is part of a grid or flex layout, for example.

There's also a separate, smaller bug, which is related, in a way: The main `limel-tooltip` element, while having a size of 0 by 0 pixels, is still part of the normal render flow (it currently has `display:inline`), which can cause issues with the alignment of the target element. If we solve the above bug, this one should be trivial to solve, since we could probably just give it `position:absolute` instead, and the consumer also no longer needs to place the `limel-tooltip` element right next to the target element.

## Expected behavior

The popover should be positioned in relation to the target element.

## Environment

- **lime-elements** version: v33.14.0-next.8
- Framework used: Found in AngularJS, but should be easily reproducible anywhere.
- Logs:

**Comment by Kiarokh** [comment]
I changed the title, since the word "popover" made me think that we're talking about the combo use of `limel-popover` and `limel-tooltip` together on the same element.

**Comment by adrianschmidt** [comment]
Good! It's much better now 👍

**Comment by adrianschmidt** [comment]
This has not been fixed:

![image](https://user-images.githubusercontent.com/154725/141286813-762563ed-4af0-4fcf-afb7-de51c981c382.png)

**Comment by Kiarokh** [comment]
oh I think we forgot to remove the wrong `fix:` link from the PR! Good that you noticed

**Comment by adrianschmidt** [comment]
I think I understand what the problem is here. `limel-portal` is hardcoded to use its host element as the element to position the portal in relation to. Fixing this should be a simple matter of adding a property where limel-portal can be given a target element, and have limel-portal fall back to using its host only if no target has been supplied. Hopefully 😅

**Comment by eketorp** [comment]
When this is fixed, look at https://github.com/Lundalogik/crm-feature/issues/2590

**Comment by jgroth** [comment]
Hopefully some day we can get rid of the portal component, it's hard to both understand and maintain :smile: Since the browser now has the [top layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer) we should be able to use that for components that needs to be displayed above other content without relying on z-indexes which does not always work. Unfortunately the only way to use the top layer right now is through the HTML `dialog` element with the [`showModal`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal) method which might have weird side effects if we use it on componenets like tooltips :thinking: 
The [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) should probably be used instead to access the top layer, but it is still experimental. There is also the problem with positioning though which [CSS anchor positioning](https://developer.chrome.com/blog/tether-elements-to-each-other-with-css-anchor-positioning/) should be able to solve, but that seems to be even more experimental :smile: 

That's all stuff for the future though, it would probably be possible to solve this with our current implementation and Adrians suggestion is probably a good starting point :slightly_smiling_face:

**Comment by Kiarokh** [comment]
Future sounds promising, but this issue is blocking sooooooo many things, and causes soooo many CSS hack just make things "look alright". It'd be really good if we could solve this and not get annoyed and surprised every time the tooltip is used. In many cases, we chose not to use the tooltip component, and instead go for the `title` attribute.

**Comment by Kiarokh** [comment]
I can't believe this is finally in review 😍
