### ISSUE TITLE
Month date picker skips year

### ISSUE THREAD

**Issue by eketorp** [Lundalogik/lime-elements#1455]
## Current behavior

Skips year 2023
![month skip](https://user-images.githubusercontent.com/58422324/142593443-8034f508-a49a-4aa4-88c2-a5fdf1f35bb5.gif)

1. Go to lime elements docs
2. Go to month date picker
3. Scroll between years
4. Skips year 2023

## Expected behavior

Not skip 2023

## Environment

- **lime-elements** version: 34.0.1

**Comment by adrianschmidt** [comment]
# 😮 🧐

That's weird…

And it apparently gets weirder, because I just did some testing:

| month selected | year skipped |
|---|---|
| 12/2021 | 2022 |
| 11/2021 | 2023 |
| 10/2021 | 2024 |
| 9/2021 | 2025 |
| 8/2021 | 2026 |
| 7/2021 | 2027 |
| 6/2021 | 2028 |
| 5/2021 | 2029 |
| 4/2021 | 2030 |
| 3/2021 | 2031 |
| 2/2021 | 2032 |
| 1/2021 | 2033 |
| 12/2019 | 2020 |
| 11/2019 | 2021 |
| 12/2018 | 2019 |
| 11/2018 | 2020 |

I haven't tested every single month for any year other than 2021, but the pattern seems to hold.

If you hover the year, to get flatpickr's original year navigation, and click through that, the year isn't skipped (which isn't that weird), but if you then navigate with our own arrows again, the year skipped has moved so that it's still as many clicks away as it was before, but not on the same year as it was. Example:

1. Select 11/2021.
2. Press the right arrow to go to 2022, next press skips over 2023 and puts us on 2024, next step puts us on 2025. Now the "year skip" would happen if we press the left arrow twice (it would go to 2024 on the first click, then to 2022 on the second).
3. Instead, hover the year, and press the down-arrow 4 times. You'll see it step back through 2024, 2023 and 2022, and finally land on 2021, having not skipped any year.
4. But remember, the "year skip" was "two clicks to the left", right?
5. Click the left arrow, putting you on year 2020.
6. Click the left arrow again. Boom! 2019 is skipped over and you end up on 2018.

With this, I think I have a rough idea of what the problem is. When clicking the arrows, I think we're keeping track of the months in some way, and instead of "moving 12 months", we "move 13 months". When the "display month" is December, the next year will be skipped, because we'll add a year, moving us to the next year, but then we also add another month, moving us to the next year _again_, moving 2 years in total.

**Comment by eketorp** [comment]
Great troubleshooting!

**Comment by eketorp** [comment]
WP post: https://limetech.workplace.com/groups/limecrm/permalink/4160239750747043/

**Comment by eketorp** [comment]
But don't each year have 13 months in China? 🤔 How will this affect Chinese users? 🙈

**Comment by anderssonjohan** [comment]
@adrianschmidt Reminds me of this one when I complained about the fact it took 12 clicks to get to the next year using those buttons. https://github.com/Lundalogik/lime-elements/issues/1247
