### ISSUE TITLE
Table: Hide sorting arrows, show them if sorting is active

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1830]
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/35954987/189143111-03e2fb3b-f12d-4c79-b996-54d4e2f5e3e2.png">

Displaying sorting arrows on all column tables is: 
- visually too noisy,
- misleading, since when there is no sorting, why should we display an arrow that miscommunicates the meaning of sorting
- makes it hard to see which columns has an active sorting (the difference is not so clear)

Displaying the sorting arrow is only correct when the column is actually sorted.

## Additionally, the sorter arrow points to the wrong direction

For numeric values smallest should be first, when sorting is _ascending_, and visa versa, but today it's visualized the other way. 
<img width="48%" alt="image" src="https://user-images.githubusercontent.com/35954987/189638261-0fde331f-44b6-49a7-b8db-ee3edf229e59.png"> <img width="48%" alt="image" src="https://user-images.githubusercontent.com/35954987/189638354-5ae1d507-0349-464b-899e-47a7ff9fd892.png">

for alphabetical sorting letter A should be first should be first, when sorting is _ascending_, and visa versa, but today it's visualized the other way. 
<img width="48%" alt="image" src="https://user-images.githubusercontent.com/35954987/189639174-10437ab4-735e-4281-a916-92d0eebd8788.png"> <img width="48%" alt="image" src="https://user-images.githubusercontent.com/35954987/189639236-e2e633c3-2aab-4270-b04c-441d3140b704.png">

**Comment by adrianschmidt** [comment]
Will there be any indication for the user that they can click to sort? 🙂

**Comment by Kiarokh** [comment]
Of course! 😊

**Comment by Kiarokh** [comment]
With this PR:


https://user-images.githubusercontent.com/35954987/189644068-a3d77013-6fa5-4eff-a42a-b48028b33d75.mov

**Comment by vicgeralds** [comment]
> Additionally, the sorter arrow points to the wrong direction

Does it really? I'm always confused about the sorter arrow direction, but when I look at Finder on Mac it points up when sorting in ascending order.

**Comment by Kiarokh** [comment]
🤔 hm... 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/35954987/189844622-1415d669-56a0-4f3b-87f7-177525c34fee.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/35954987/189844728-db4f489f-0032-40c9-9c81-323822d7aeb1.png">

Yeah maybe that's an standard :/ 

Material design also has it that way:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/35954987/189845921-14287428-0dc0-4f3c-af79-02e29393d5a7.png">
However, if both Apple, Google and Tabulator have it this way, then maybe there is some convention about it. 

**So we should drop the last commit**


This one reminds me of the toilet paper orientation dilemma 😅
<img width="632" alt="image" src="https://user-images.githubusercontent.com/35954987/189845200-8542ade8-01f7-4738-a758-41e763e94a95.png">

**Comment by LucyChyzhova** [comment]
I think that Apple's solution works naturally due to the icon they used.   So here for instance they render results from a broader to narrow scope.

![Screenshot 2022-09-13 at 10 29 31](https://user-images.githubusercontent.com/50618208/189851892-604024f6-4068-42f4-9fb0-276e39788c39.png)

![Screenshot 2022-09-13 at 09 59 00](https://user-images.githubusercontent.com/50618208/189851115-8dffba45-de9c-48b0-9358-6f06a76b49d0.png)

**Comment by Kiarokh** [comment]
OK dropped the last commit

**Comment by Kiarokh** [comment]
even though I completely dislike the convention

**Comment by vicgeralds** [comment]
> even though I completely dislike the convention

Yeah, I agree that it feels wrong. Because I think ascending means A -> Z  or low -> high and descending means reverse order, so <-

But the word ascending actually means to move upward, so then ⬆️  makes total sense. If seen as a less-than/greater-than symbol, A < Z (ascending) vs A > Z (descending) also makes sense I think. Still feels wrong 😄

**Comment by vicgeralds** [comment]
@Kiarokh if it still feels wrong, try to think ^ for Ascending, down for Descending 😄

**Comment by adrianschmidt** [comment]
People, please, you know you could have saved yourself loads of commenting if you had just pinged me first 😝

It's 🔼 for Ascending and 🔽 for Descending. But I _think_ it actually hasn't got anything to do with the relationship between "ascending" and "up" and "descending" and "down", originally (although it's certainly very useful for remembering). I believe there's a reason Apple are using wedges or triangles, not arrows, because (like Lucy touched on) the shape itself indicates the order. 🔼 visually indicates that smaller things are on top, and larger things are below. 🔽 visually indicates larger things on top.

It's perhaps a _smidge_ less intuitive for alphabetical order, but I think you will struggle to find anyone who thinks that to represent letters with numbers, Z should be represented by 1, and A should be represented by 26…

This is one of those rare cases where I think it doesn't matter how common it is to use one or the other. There is one correct way, and one incorrect way. This is a hill I will die on.

**Comment by adrianschmidt** [comment]
The reason "ascending" is called "ascending", is that the first value is smaller than the second value. So the values become bigger as you go further through the list. The values are "ascending", from smaller to bigger.

**Comment by Kiarokh** [comment]
So in this case, Apple's design is correct, but it is confusing because it looks like a dropdown carret.

And material design's arrow is incorrect because it visualizes a direction in which things are ascending or descending, but in reverse. 

However, they have set the tone, and as @eketorp said:
> If you want my two cents: i never look at the direction of the arrow. It takes more brain effort to figure out the direction I want, see if that direction is applied and if needed, apply that direction. I just click the heading until it's sorted the way I want, even it was sorted like that in the first place. Stupid, you might think. But that's what I do. Not saying anything on how everyone else does it.


And I'd say, arrows or carets aren't visually enough. We'd need more clear iconography like below.
<img width="834" alt="image" src="https://user-images.githubusercontent.com/35954987/189917903-8459ff3b-1ba5-4e87-9a0a-05f9f28bb07f.png">

Anyhow, this is not a big deal. Let's move on. People figure out what it means, by looking at the data and flipping the sorting anyways. ;)
