### ISSUE TITLE
Badge icons on limel-select

### ISSUE THREAD

**Issue by TommyLindh2** [Lundalogik/lime-elements#2017]
## New feature motivation

When using `limel-select` you cannot use badge icons.

## New feature description

Be able to choose if the limel-select shows the icons with a badge.
But still want to be able to set color of both background and icon.

## New feature implementation

Add a property of type boolean on the limel-select called something like `badgeIcons` 
Be able to control the color of the icon using `iconColor` and maybe `fillColor` or something like that?

**Comment by TommyLindh2** [comment]
@Kiarokh @LucyChyzhova

**Comment by Kiarokh** [comment]
@LucyChyzhova and I was thinking about this issue, and we don't think using badge icons is a good idea. 
With colors, all we want to do is color coding things, and use the color as a visual reference. So, it doesn't really make sense to have an icon, and apply the color only to its circular background. 

We think if something should be color coded, it should be on the whole icon+text. 
Check this image for inspiration:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/35954987/221816685-e169ce01-c219-498b-a93a-5466956fe233.png">

Also, this requires us to go through the design and features of the current Option Visualizer, and revisit how it works and how it should be working, to provide a more useful and beautiful UI design. 

As we expressed many times before, we wish you sync such decisions **_before_** making something, not **_after_**. 😊 🙏 

@blombergedvin @TommyLindh2 @BjornOstberg

**Comment by TommyLindh2** [comment]
I totally agree that badges is a bad idea, the reason why it's in there is for a few reasons.

1. Lime-elements have badges and supports it. 
2. The web client uses badges on for example relations, so it actually gets more consistent with badges as of now.

If I remember correctly there were plans to remove the badge part on relation-picker as well. I think it would be nice to maybe make a release that removes badges in our option-visualizer when it's done in the web client as well. I think that we could release that without even having a breaking change. It's just visual changes. 

So if that's the case I think we can close this issue without making any changes.

@blombergedvin do you agree?

**Comment by Kiarokh** [comment]
> Lime-elements have badges and supports it.

I know... 😿 badge (_note for future generations:_ I'm referring to the colorful backplate of icons) in itself is not inherently bad. But usage of it should be done very carefully and purposefully. In a UI, colors generally need to be used very _stingily_ and purposefully.

> The web client uses badges on for example relations, so it actually gets more consistent with badges as of now.

We actually had a few rounds of removing badges from everywhere. See a memory of how things could look in the old web client 👇 😄 
![0-customer-card-today](https://user-images.githubusercontent.com/35954987/221892737-1c3af282-1ff4-45f6-b885-8a6065a677c2.png)

Here is [an example of such issues](https://github.com/Lundalogik/crm-feature/issues/1886), and arguments about why badges are removed. So I really don't want them back again 😅 

I think the only place the badges remain today are the relation pickers. And there were some technical difficulties that I had, and couldn't fix the problem alone. And then we never had the time to go back to them when I improved my coding skills. Which is why they are still left there. I hope I can remove them.

I think we can close this issue and get back to this when we look into the design of Option Visualizer again.
Here is an inspirational image form a competitor. 

<img src="https://attio.com/build/_assets/build-tab-refine-desktop-MHSSPGB6.webp"/>

**Comment by TommyLindh2** [comment]
Yes, it’s an easy fix to migrate the config and silently remove the badges

**Comment by Kiarokh** [comment]
Thanks 😊 
I think if there are already badges configured, we can render them like this:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/35954987/222079377-85e69984-9687-4083-ac72-52dfa1489069.png">

So we don't have to migrate, just tweak the rendering in the UI. Let's talk about it when we meet ;)

**Comment by TommyLindh2** [comment]
The issue today is that people use it together with icons and therefore expects an icon with the badge. But maybe that can be fixed as well

**Comment by Kiarokh** [comment]
I see. We can have that as a deprecated thing then perhaps.
But people shouldn't decide. ;P

**Comment by Kiarokh** [comment]
closing this and not gonna read all the history... if anyone disagrees, let me know. But call me please and don't force me to read all this ☝️
