### ISSUE TITLE
limel-collapsible-section: clicking a disabled action button lets the click through to the collapsible-section and opens or closes it

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#2052]
## Current behavior

Clicking a disabled action button lets the click through to the collapsible-section and opens or closes it.

https://user-images.githubusercontent.com/154725/213476516-75f06877-3289-440f-a068-495664b39081.mov

1. Go to the _Example with actions_ example in [the docs](https://lundalogik.github.io/lime-elements/versions/next/#/component/limel-collapsible-section/).
2. Click the disabled action button (the one with the refresh-icon).

- The collapsible section expands, or collapses. Also, the mouse cursor has the wrong icon, indicating that interaction is possible.

## Expected behavior

The click should be captured and prevented from expanding or collapsing the section. The mouse cursor should be one that does not indicate that interaction is possible.

## Environment

- **lime-elements** version: v36.3.0-next.2
- Framework used: Reproducible in the docs
- Logs:

**Comment by Kiarokh** [comment]
It is possible to treat the symptom of this issue in the collapsible section, in one or another way (like the creative way @LucyChyzhova has suggested in the linked draft-PR). 

But the source of this problem is here: https://github.com/Lundalogik/crm-feature/issues/3317 We need to solve it once for all interactive components like buttons, icon-buttons, shortcut, toggle, etc… Otherwise, we will have this problem happening in other contexts too. We need to get rid of the CSS hack that we have done on all these components.

**Comment by LucyChyzhova** [comment]
@Befkadu1 and I were working on this: https://github.com/Lundalogik/crm-feature/issues/3317 and it seems like a non-related issue.  After implementing a solution described in that thread it was still possible to click on a disabled button and got a collapsible section opened.

**Comment by LucyChyzhova** [comment]
@adrianschmidt Could you please check two linked PRs - they both fix this issue but in a slightly different ways. 
I will unassign myself and put it in the review column. However, would love to get your input ❤️ (whenever you have time) 
Thanks.

**Comment by adrianschmidt** [comment]
> Could you please check two linked PRs - they both fix this issue but in a slightly different ways.

I think we should certainly do #2230 👍

We might want to do #2235 _as well_, but preferably without making it "un-shadowed".

**Comment by LucyChyzhova** [comment]
cool! 🚀 thanks a lot for your input! ❤️

Also for the #2235 we need more fixes, I just added a fixup. However, even now it's quite tricky.

**Comment by Kiarokh** [comment]
I think #2235 is not really viable yet and doesn't really do what we want. By removing the shadow, we're still returning the `<button>` element inside something else, another element. We want to return nothing but a button. The host should be the button itself. Otherwise, onClick from outside will still do the same shit that it has always been doing. Not sure if setting `role="button"` on the host, and removing the inner button would do the tick. I'll check this too.

Anyhow, for #2230 I'm not 100% happy yet. I think we have other CSS hacks to do this more globally. I'll also check that. So Please don't merge #2230
