### ISSUE TITLE
Badge: render even without label.

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2140]
<img width="229" alt="Screenshot 2023-02-20 at 16 51 30" src="https://user-images.githubusercontent.com/35954987/220151660-93f39cef-3ae0-47a4-bf73-e82618f4cbba.png">

There are many scenarios where we want to display a badge, but empty. The reason could be indetermination. Like, when the system knows that there is something that requires user's attention, but there is no quantity for it. We don't know how many there are... we just know that there is something.

**Comment by adrianschmidt** [comment]
Yeah, nice, seems like an obvious addition! 👍

There are several possible solutions of course, but I would suggest that we simply update the type of the `label` property from `string | number` to `string | number | boolean`, and if the value is `true` the badge, but with no text.

Now, admittedly, when I thought of this solution, I was thinking the `label` property was called `value`—in which case I think this would have been a perfect solution—but with the property called `label`, it will be a bit weird that `label={true}` will mean that we render the badge, but with no label… 😬

But I also don't love the thought of adding another property for this…

(And just in case anyone comes up with the idea of typing `label` to `string | number | boolean`, but then let `label={false}` mean that we render the badge, but without a label, I think that will be annoying to implement. I also just generally feel quite apprehensive towards that solution, but perhaps that's just because I'm stuck in my original lines of thought… 🤷‍♂)

**Comment by vicgeralds** [comment]
>  I would suggest that we simply update the type of the label property from string | number to string | number | boolean, and if the value is true the badge, but with no text.

My first thought was that this seems like a nice solution, but then yes I totally agree about your concerns when the property is called `label`.

> But I also don't love the thought of adding another property for this…

Can't we just make the label property optional?

We can still use a boolean to determine if a badge should be rendered or not in [dock types](https://github.com/Lundalogik/lime-elements/pull/2139/files#diff-c567d7364e9bb5d7817a94c77846d55547529dfd06b828f1e303a8a7c9d4c867R47) for example.

**Comment by Kiarokh** [comment]
Generally I think we should have given these naming more thoughts from the beginning 😓 Sometimes we call it `text` sometimes `label` sometimes `value`. For badges I think it would have made a lot more sense to call it `value`.

> Can't we just make the label property optional?

Yes, can't we write like `if (label.length === 0)` or something similar?

**Comment by adrianschmidt** [comment]
Ah! For whatever reason (I suspect because of how the issue title is worded), I had assumed that it was already optional, and that leaving it empty meant that no badge was rendered. But that's not the case. I tried removing the attribute with the browser dev-tools, and that worked just fine! 👍

So we should really just need to add a question mark to the property, and this should be done 😄 🙌

**Comment by Kiarokh** [comment]
> So we should really just need to add a question mark to the property, and this should be done 😄 🙌

Oh, well… I think we have been living under some illusions for a few years actually. [`3550d6f` (#2144)](https://github.com/Lundalogik/lime-elements/pull/2144/commits/3550d6f376897ce8d7a223c69f5a6f1388753bdb#r1113151744)
