### ISSUE TITLE
Keyboard opens automatically when dialog is rendered in android

### ISSUE THREAD

**Issue by omaralweli** [Lundalogik/lime-elements#2420]
## Current behavior

The bug was discovered in esign #https://github.com/Lundalogik/limepkg-esign/issues/1405 where a phone keyboard automatically pops up every time the `sign the document` button in the portal is pressed. But after further investigation it looks like the behaviour is linked to `limel-dialog`.  

1. Open any `limel-dialog` from an android phone.
2. 
![2](https://github.com/Lundalogik/lime-elements/assets/77667105/5b755652-cf5d-4513-b153-23e753794282)

## Expected behavior

The keyboard does not automatically pops up on an android phone when `limel-dialog` is rendered and there are no text input fields.

**Comment by justFredster** [comment]
@Kiarokh @LucyChyzhova is this something you can have a look at? Or is it @adrianschmidt? 

It is really annoying in the eSign portal, when you click the "Sign" button, but shouldn't type any text. See issue in eSign repo for more info: https://github.com/Lundalogik/limepkg-esign/issues/1405

**Comment by Kiarokh** [comment]
😮 is it because we are setting `focus` on the surface maybe Adrian?

**Comment by adrianschmidt** [comment]
I know we had a problem that the focus-trap* that MDC was using didn't work because it didn't support shadow-DOM. I think that was later solved by someone, I think it might have been @maltja. If I recall correctly, the solution involved adding a hidden element, which we set focus to. I'm not sure about this, but it's what my vague memories suggest. If that's correct, and that element is something like a visually hidden input field, that would explain why the soft keyboard shows up on mobile devices… 😕

*) A focus-trap is a piece of code that sets focus within a certain element (like a modal), and prevents focus from leaving said element as long as it is open (focusing elements inside the modal should work fine, but tabbing out of the modal and focusing elements on the page behind should be prevented). If it's a really good focus-trap, it might also cover placing focus back on the element that was focused when the focus-trapped element (the modal) was opened.
