### ISSUE TITLE
input field: placeholder text is invisible in dark-mode

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2658]
<img width="359" alt="image" src="https://github.com/Lundalogik/lime-elements/assets/35954987/efe3fb9b-26c4-45d8-ba13-db08178f9dba">

**Comment by adrianschmidt** [comment]
I suspect this has already been fixed, since the placeholder seems to be working in the docs for the latest release:

<img width="578" alt="image" src="https://github.com/Lundalogik/lime-elements/assets/154725/8bf4dfc4-7804-414d-9296-dfd5a9bb25ee">

<img width="573" alt="image" src="https://github.com/Lundalogik/lime-elements/assets/154725/6f5e0f9c-ef9c-4794-8804-7a4481fea14e">

**Comment by adrianschmidt** [comment]
I'll close this. Open it again if there's still a problem! 👍

**Comment by Kiarokh** [comment]
I'm gonna rewrite the input filed and dematerialize it anyways. So we will fix it then if it's not fixed

**Comment by adrianschmidt** [comment]
Nice!

limel-input-field has grown to be a really quite complex component. It would be nice to see if we can perhaps modularise it a bit, to make each piece simpler, for example. Hit me up if you want to look at that together 🙂
