### ISSUE TITLE
limel-input-field: `pattern` property does not work

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#2742]
## Current behavior

1. Go to https://lundalogik.github.io/lime-elements/versions/next/#/component/limel-input-field/ and find the example called _Input Field with pattern_.
2. Enter some value not following the required pattern, like `asdf`.
3. There is no indication that the value is invalid.
4. Blur the input element.
5. There is still no indication that the value is invalid.

## Expected behavior

Either the field should be shown as invalid (at the very least at point 5 above, but probably already at point 3), _or_ we shouldn't have this pattern property at all, and feature should instead by supported in some other way (through external validation, perhaps via the schema for `limel-form`).

## Environment

- **lime-elements** version: Reproducible in the docs for the latest full release (v37.0.0) and the, at the time of writing, latest next-version (v37.1.0-next.95)
- Framework used: Reproducible in the docs
- Logs:

**Comment by vicgeralds** [comment]
Fixed by https://github.com/Lundalogik/lime-elements/pull/2869/commits/2a23f3c9abe78f7a5e1f4c80340fec58dd09a9ce

The regular expression was no longer valid. Found out it's now compiled using the `v` flag, which is more strict with character classes: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern#overview
