### ISSUE TITLE
Conditional Buttons Not Showing Up in `limel-dialog`

### ISSUE THREAD

**Issue by Befkadu1** [Lundalogik/lime-elements#3265]
Buttons placed in the footer of the limel-dialog are not rendered when shown conditionally.

Currently, the footer of the limel-dialog is enabled in the componentWillLoad method, which is only called once during the component's lifecycle. If a button is conditionally shown after the render function is executed, there is no way for the button in the footer to be rendered in the DOM when the condition is met.

**Steps to Reproduce**:
1. Place a button in the footer of a limel-dialog.
2. Set the button to be conditionally shown (e.g., based on a state or prop change after the initial render).
3. Observe that the button is not rendered in the footer even when the condition is satisfied.

**Expected Behavior**:
The button should be rendered in the footer of the dialog when the condition is met, even if it's conditionally shown after the initial componentWillLoad call.

**Actual Behavior**:
The button is not rendered in the footer when the condition is met. The footer is enabled during componentWillLoad, which only occurs once, preventing the button from appearing later.

**Comment by adrianschmidt** [comment]
The reason for this behaviour is that if the action button slot is empty when the dialog is created, we remove the slot, because otherwise the empty slot takes up some space at the bottom of the dialog.

However, that solution isn't great anyway, because 1) you can't add buttons later, as described in this issue, and 2) if you have buttons when the dialog is created, and then hide or remove them, you don't get the same result as if the dialog was loaded with no buttons.

So it would be great if we could find a solution that makes the dialog look good regardless of whether there are action buttons or not, _without_ removing the slot 🙂

**Comment by Kiarokh** [comment]
Wow... this is not good. We could easily fix this with CSS: If you fix this issue with component lifecycles, I will fix the layout problem that yo are describing @adrianschmidt . We can work on it together if you want..

**Comment by adrianschmidt** [comment]
Sure! 👍

**Comment by Befkadu1** [comment]
@Kiarokh @adrianschmidt you guys are amazing!
