### ISSUE TITLE
Snackbar never shown when timeout is -1

### ISSUE THREAD

**Issue by vicgeralds** [Lundalogik/lime-elements#3278]
## Current behavior

If limel-snackbar is rendered with `timeout` set to -1, it becomes hidden immediately.

## Expected behavior

Even if not documented, this used to mean disabling the timeout https://www.npmjs.com/package/@material/snackbar#javascript-api

Lime CRM currently relies on this behaviour when notifying "Failed to save object" error.

## Environment

- **lime-elements** version: 37.64.2

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have identified the issue in the `limel-snackbar` component where setting the `timeout` to -1 causes the snackbar to hide immediately. To fix this, I've updated the `handleOpen` method in the `Snackbar` class to treat negative timeout values as persistent (no timeout). Here's a summary of the changes:

1. Modified the `handleOpen` method to check if the timeout is greater than 0 before setting the timeout.
2. Updated the JSDoc comment for the `timeout` property to clarify the behavior with different values.

These changes ensure that setting `timeout` to -1 (or any negative value) will make the snackbar persistent, matching the expected behavior described in the problem statement.

I also created pull request: https://github.com/Lundalogik/lime-elements/pull/3279


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission
