### ISSUE TITLE
setting focus on a limel-input-field's input element doesn't work

### ISSUE THREAD

**Issue by joelricci** [Lundalogik/lime-elements#411]
## Current behavior

When explicitly setting focus on a `limel-input-field` element, it won't focus (despite selecting the actual `<input>` element inside its shadowDOM).

## Expected behavior

Input element should focus.

## Environment

- **lime-elements** version: 22.3.1
- Framework used: LWC 2.1.0, Web-Client 43.23.2

**Comment by adrianschmidt** [comment]
> When explicitly setting focus on a `limel-input-field` element

I assume what you're trying to do is setting focus programmatically, rather than clicking on the element?

If you actually select the `<input>` element and focus that, I don't really have any idea why that doesn't work. But unrelated to that, I think it would be very nice if the consumer didn't have to worry about the internal structure of the component. If the component could be focused, and it would detect that and move focus to the input field, that would be great (assuming there are no unintended consequences). If that isn't possible, perhaps the component could be given a `.focus()` method or something.

**Comment by joelricci** [comment]
> > When explicitly setting focus on a `limel-input-field` element
> 
> I assume what you're trying to do is setting focus programmatically, rather than clicking on the element?

Yes, correct. Since setting _"autofocus"_ on the element didn't work, I tried setting it programmatically instead, which didn't work either.

> If you actually select the `<input>` element and focus that, I don't really have any idea why that doesn't work. But unrelated to that, I think it would be very nice if the consumer didn't have to worry about the internal structure of the component. If the component could be focused, and it would detect that and move focus to the input field, that would be great (assuming there are no unintended consequences). If that isn't possible, perhaps the component could be given a `.focus()` method or something.

I agree. If it could behave like a standard <input> field that would be great ofc.

**Comment by adrianschmidt** [comment]
> Yes, correct. Since setting "autofocus" on the element didn't work, I tried setting it programmatically instead, which didn't work either.

Ah, yeah, we ought to have `autofocus` as an attribute as well, since that's tangential but separate functionality.

Both ought to work, but one might be easier to implement than the other.

**Comment by maltja** [comment]
This [PR](https://github.com/Lundalogik/lime-elements/pull/1227) makes it possible to set focus on input field with .focus().

**Comment by adrianschmidt** [comment]
I think we can close this issue then 🙂
