### ISSUE TITLE
Number field is changed when the field is in focus and using mouse scroll

### ISSUE THREAD

**Issue by magnusfagerlund** [Lundalogik/lime-elements#498]
## Current behavior

The number field is changed (increased/decreased value) in add-new dialog when focused and scrolling using mouse/keypad (see video).

![number input scroll](https://user-images.githubusercontent.com/154725/67931264-c5f5f000-fbc1-11e9-862c-d5633e941a8c.gif)

[Full size video here.](https://github.com/Lundalogik/lime-elements/files/3791183/20df750374482efb41ad6751f10e1343.zip)

## Expected behavior

Only the add-new dialog should scroll up and down, not the value in the field.

## Environment

- **lime-elements** version: 24.6.0

## Info from customer report

I am currently on Chrome (ver. 78, if that matters) on a MacOS. But it seems to be a problem with Integer field which only occurs in the pop-up window. There’s an event listener on the mouse scroll wheel that only shows up in the pop-up for the fields with type=”number” .

![integer bug](https://user-images.githubusercontent.com/7524499/67900048-d7a8aa80-fb63-11e9-840c-4350cc5bf063.png)

**Comment by adrianschmidt** [comment]
I'm guessing this is behaviour from MDC, which would mean that it's probably according to the Material spec. Although it might be configurable.

Personally, I agree that the positive value of being able to scroll to change the input-value is less significant than the negative value of possibly changing the input-value accidentally, because of our "always edit" behaviour. However, if the behaviour is indeed implemented in the MDC-component, and it doesn't provide a config-option, overriding it might be very difficult…

**Comment by adrianschmidt** [comment]
This was fixed by #602
