### ISSUE TITLE
limel-select: OnChange event triggered twice when value is selected

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/lime-elements#520]
## Current behavior

When you change a value of a limel-select the method bound to the event triggers twice. First with the original value and then with the value that you chose. If the limel-select doesn't have a value and then you choose one, it only triggers one.

## Expected behavior

Preferably the event only triggers once. 

## Environment

- **lime-elements** version: Not sure how to check but I am using Lime CRM Server 13.0.3.8.

**Comment by adrianschmidt** [comment]
It looks like this was fixed in #416 which was released in lime-elements v23.0.1

I'll see if I can find out what version of lime-elements is in which version of the server.

**Comment by LarsCJensen** [comment]
@limetech/lime-elements: "23.0.0"

**Comment by adrianschmidt** [comment]
> @limetech/lime-elements: "23.0.0"

Hmm… that's interesting… what does it say for lime-webclient? When I looked at the dependencies in the release, and traced it back through the version of lime-webclient, it looked like that release ought to use lime-elements v24.1.1. But that data from the console isn't lying, so it seems I missed something along the way.

The next release of Lime CRM Server should have the fix for limel-select though. Not sure when that's planned, but since we're on the last week of our current cycle right now, I assume the next release is planned shortly after that.

**Comment by LarsCJensen** [comment]
@limetech/lime-elements: "23.0.0"
@limetech/lime-web-components: "2.1.0"
addon_followup: "0.2.0"
addon_infotiles: "4.2.3"
crm_customer_limetech: "1.4.0"
lime-webclient: "43.26.3"

**Comment by adrianschmidt** [comment]
Ah, yeah, that makes more sense. Then I was looking at one release later than I should in lime-webclient.

The latest CRM Server nightly is 13.2.0.328. Feel free to try that and see if the problem persists. I can slack you the link if you need it.

**Comment by adrianschmidt** [comment]
Closing this. Please do comment again if the next release doesn't resolve it.
