### ISSUE TITLE
scrolling removes content of pickers' lists

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#705]
![scroll-bug-2](https://user-images.githubusercontent.com/35954987/80185715-16985400-860d-11ea-8469-1be08a49a0da.gif)
__________________________

![scroll-bug-1](https://user-images.githubusercontent.com/35954987/80185729-1bf59e80-860d-11ea-997c-8afe4c28e37c.gif)

**Comment by jensgustafsson** [comment]
I would like to say that we could down prioritize this one. Or what do you say @magnusfagerlund? I think it's quite a big investment to solve this and our current design doesn't solve this in a good way either.

**Comment by magnusfagerlund** [comment]
I would like to get the issue described a bit before giving my opinion. @Kiarokh could you provide a gif?

**Comment by jgroth** [comment]
This is probably not an easy fix. In order to have dropdowns not being cutoff by dialogs etc we had to move them in the DOM from the context of the component out to the body element. When doing this, we made this limitation on purpose since it is hard to know if the element should scroll or not, and where the new position should be. It should still be possible to scroll inside the list itself though

**Comment by Kiarokh** [comment]
![scroll-bug-3](https://user-images.githubusercontent.com/35954987/80185964-8a3a6100-860d-11ea-8b14-f5ba4e751506.gif)

**Comment by magnusfagerlund** [comment]
I've been testing and comparing with our current on-prem release (testing in Sublime) and it feels like a quite big regression tbh. It works well in Sublime, but not at all that well in current lime-webclient release. I will post gifs to show shortly.

**Comment by jensgustafsson** [comment]
@magnusfagerlund yes we discussed it after standup. We will try to fix the issues

**Comment by magnusfagerlund** [comment]
👍
