### ISSUE TITLE
Too small margin over limel-select

### ISSUE THREAD

**Issue by sofiehelgesson** [Lundalogik/lime-elements#728]
## Current behavior

I have a dialog with both input fields and limel-selects and the margin for limel-select is smaller than for the limel-input
![image](https://user-images.githubusercontent.com/24894627/80194990-87466d00-861b-11ea-9685-9542fb2e8e12.png)

## Expected behavior

the same margin for both limel-input and limel-select

## Environment

- **lime-elements** version: 22.3.0

**Comment by adrianschmidt** [comment]
This issue is very similar to #626. At least in this one, the label doesn't actually *overlap* the preceding component 😄

Ping @Kiarokh: These two issues seem like something you could probably find a good solution for?

**Comment by Kiarokh** [comment]
Tnx Adrian. Yes I'll check both of them up ;)

**Comment by Kiarokh** [comment]
@adrianschmidt & @JohannesHansen I'm fixing this issue and unifying all these different fields. 

But I wanted to pick your brains about another thing regarding the layout of these fields. In the attached picture above, we see that all fileds are tightly placed after each other. There is no distance between them, which doesn't provide a good UI design. I believe that the reason is the absence of `mdc-text-field-helper-text` under the fields in this custom implementation.

In LimeElements' own "Form" example, these divs exist (but they're empty), which will automatically make the layout more organized. 

If we remove them, same problem happens there too.
<img width="1534" alt="Screen Shot 2020-05-08 at 13 58 38" src="https://user-images.githubusercontent.com/35954987/81403896-a9b8aa00-9134-11ea-83b0-6c4d56d0e873.png">

That's also one of the reasons why they will render like this [in the other issue](https://github.com/Lundalogik/lime-elements/issues/626):
![image](https://user-images.githubusercontent.com/35954987/81403928-bc32e380-9134-11ea-832e-bf7c8eb65483.png)
_________________
Anyhow, in reality, we cannot expect the empty helper text containers to be present in the `dom` all the time, thus we may easily get this unpractical form layouts everywhere. Unless the consultants make sure to do some styling themselves, which is probably something that we really want to avoid; right?

So I'm thinking about having some default margins (all sides) in all these types of fields which can be used in forms. Such as inputs, sliders, pickers, selects, (more...?) 

Default margins will be there with or without help texts. In other words, all of these elements will have the same height and some distance from each other, thus would align correctly when placed beside each other in a row. And they will also have some vertical distance when placed in a column. 

Do you also thing this is the right track to go?

The only risk I can assess now is that we must also make sure that other elements such as a modal's header or a card's header can fit these mentioned elements in themselves. It may mean they shouldn't have a fixed height or have a `flex` layout that can align items vertically correct, when some larger element such a s a `select` dropdown appears in them. For example:
![image](https://user-images.githubusercontent.com/35954987/81404710-6f500c80-9136-11ea-8db2-69f3d3d8649e.png)
Imagine if we had help text below the select elements in the header.

Thoughts?

**Comment by adrianschmidt** [comment]
If we want the space, I can see no reason for not just adding the helper-text elements. They're meant to be there, but some previous designer didn't believe in white-space, so we had to remove them.

**Comment by Kiarokh** [comment]
In whitespace, we trust! :) 

But my point is that the helper texts are optional/conditional/dynamic. They may be there or may not be there, or pop in when needed (e.g. showing errors). We can't or shouldn't let them define the UI's constrains? 

If we go the way I suggested, do you see any other risks?

**Comment by adrianschmidt** [comment]
The *texts* are optional, the text *elements* doesn't have to be. We can render the helper-text elements even if the helper-text happens to be empty.

**Comment by Kiarokh** [comment]
Gotcha! 👌⭐️

Well, that'd solve the `margin-bottom` problem at least. We can then complete the work by adding `margin-left` and `right` too. I can imagine we also need a bit of  `margin-top`. 

I wonder if it's good performance-wise to render empty divs in the dom? Imagine a form or survey with a lot of fields. This may be not a big deal; but 🤷‍♂️if it's worth it. Because we can get the same visual effect if I play with the margins too, and give a negative `margin-top` value to `mcd-helper-text-inline`.

You decide and let me know. I don't know which one is the best; as I may be missing the big picture.

**Comment by adrianschmidt** [comment]
Well, in general, I don't think it's the job of these components to provide margins, because that will make adjusting that margin to the circumstances impossible. Margins should be set by the consuming component. However, if for example `limel-form` is used, `limel-form` should set the margin between the form-components.

Whether `limel-form` should set any whitespace (be it padding on itself or margin on the contained components), I think depends on the styling of the `limel-form` component. If, for example, `limel-form` would be styled to have a visible border surrounding the whole form, then obviously we would need whitespace between that border and the components inside it, and setting that whitespace would be the responsibility of `limel-form`. But if `limel-form` is "invisible" to the user, who sees only the components inside it, then it should not create any whitespace around the components, as that is the responsibility of the visual container.

We've been down the road of components providing their own margins, and it leads nowhere good.

If we want to make it easier to set the correct "standard margins", we have to do that in some other way, for example by providing helper-classes that can be set on the container elements, adding a standard padding. That way, the padding can still be modified by the consumer, when the circumstances require it.

A simple example of why we can't add left and right margins to the form input components themselves:

Say that we add 10px margin, left and right. This looks good in a single column view. But in some other place we want a form in two columns. That form will then have 10px margins to the left, 10px margin to the right, and 20px margin in the middle. Yes, HTML *sometimes* collapses opposing margins into each other, but that requires the two elements to be right next to each other, with nothing but un-positioned edges of ancestor elements in-between, and where none of those ancestor elements have any margin or padding. There may be other rules too. If that sounds complicated, that's exactly my point. It's not something we can depend upon.

Another example is, what if most of the elements in a container are not lime-elements, but some are? The natural thing for the consumer to do is to set the whitespace they want as padding on the container, let's again say 10px. But then there's a `limel-select` among the other elements. This has a margin of 10px, and then the container has 10px padding, and those (I'm relative sure, but not quite) will not collapse, leaving the `limel-select` with 20px whitespace to the left and right.

**Comment by adrianschmidt** [comment]
Come to think of it, always rendering the helper-text element isn't going to resolve this issue, because the only thing that will do, is make the label not look incorrectly placed if, and only if, there is another input component above it, which is currently showing no helper-text. It will still look broken if placed underneath any other element, or if the input component above it happens to be showing a helper-text.

The right way to do this is to either move the label, or add some whitespace to the top of the component, so that the label correctly sits *inside* the component at all times.

**Comment by Kiarokh** [comment]
Thanks a lot @adrianschmidt really good answer! I also agree that the container should setup the rules regarding (the placement of and distance between such elements). We should just make sure to add instructions in the documentations regarding how consumers should do it; and leave the responsibility of having a correct layout design to them; which is the scary part of this approach, but hopefully the most sustainable as you say.

Also, since we leave the responsibility of layout design to consumers, we can also explain how they should do with the help text when it appears and takes space. Some dos and don'ts and good examples will do the trick.
