### ISSUE TITLE
Add colorful file-format icons for lists.

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#756]
To avoid a dull and to add more recognizability to items in File lists, we need to display real app icons with their original colors.

### This is how they would look like without this fix:
![image](https://user-images.githubusercontent.com/35954987/108515621-93479d80-72c5-11eb-86cf-3576269f9104.png)

### This is how they would look like with this fix:
![image](https://user-images.githubusercontent.com/35954987/108516147-284a9680-72c6-11eb-8b3f-33ba7456f52f.png)

**Comment by Kiarokh** [comment]
for testing, you can download this zip file, which includes fake files with the most common extensions  [Archive.zip](https://github.com/Lundalogik/lime-elements/files/6010428/Archive.zip)

**Comment by adrianschmidt** [comment]
> we need to display real app icons with their original colors

Hmm… should we really though? 🤔 I think the first example looks much better for a few different reasons. For one, it's much more aesthetically pleasing, because the second example is all over the place stylewise, and is honestly quite jarring to look at. But, more importantly, from a usability standpoint, I don't think it's a good idea at all to use the _app_ icon for files associated to a certain app. File icons are usually clearly distinguished from the icon of the app they are associated with, while of course also keeping the association clear.

I don't think the icons in the first example are marvels of usability and good visual communication, but I think the second example is worse in every aspect I can think of 😞

**Comment by Kiarokh** [comment]
you're right. Unless we change them all, there's almost no point to do this and make them look like file-icons (not app icons). However, there is the PR in case we wanna merge it at some point because we need these icons for some reason :)
