### ISSUE TITLE
Focus on datepicker

### ISSUE THREAD

**Issue by sofiehelgesson** [Lundalogik/lime-elements#764]
## Current behavior

The first time I pick a date it gets marked with the green colour which stays even when I go to another field. In the picture below I first picked a date and then I choose "Sales Status" and then both got marked.

If I go back to the datepicker and then to a new field the colour goes away but not the first time.

![image](https://user-images.githubusercontent.com/24894627/82049408-923e6b80-96b6-11ea-89a5-75b8056c2991.png)

## Expected behavior

that it gets grey, when leaving to another field

## Environment

- **lime-elements** version: 22.3.0

**Comment by Kiarokh** [comment]
@sofiehelgesson i think this issue must be solved when we solved this one: https://github.com/Lundalogik/crm-feature/issues/1019

Can you please verify, and close consequently close the issue if it's solved? Thanks. :)

**Comment by Kiarokh** [comment]
@jensgustafsson can this be something that will automatically get solved when you switch to the new date pickers?

**Comment by jensgustafsson** [comment]
> @jensgustafsson can this be something that will automatically get solved when you switch to the new date pickers?

I hope so 🙏

**Comment by Kiarokh** [comment]
@jensgustafsson @adrianschmidt should we close this issue, as it's addressed here: https://github.com/Lundalogik/lime-elements/issues/815 ? or should we link `fix:`es to them?

**Comment by adrianschmidt** [comment]
#823 (the PR for #815) already mentions that it might fix this issue too. I'll test if it does, and if so, I'll link them so that PR closes this issue when merged.

**Comment by jensgustafsson** [comment]
I've been looking in to this issue today and found out that the bug was partially fixed by #815 but still exists under a specific condition.

Right now I'm leaning towards closing this issue and marking it as "wont fix" as I believe we have other issues that's more important to fix.

Scenario when the bug still appears:

1. Set the value in the datepicker to `null` (same as setting empty string in the input field of the picker)
2. Open the picker and select a new value.
