### ISSUE TITLE
Add “label” in chipset other than “input” type on lime-elements

### ISSUE THREAD

**Issue by Befkadu1** [Lundalogik/lime-elements#800]
Today, the only chipset type that allows `label` is the `input` type. But we need even support for other chipset types which are not necessarily hosted by an interactive element such as the picker or input.

**Comment by adrianschmidt** [comment]
I changed the label from `feature` to `design`, because we should have a design discussion about this before any work is started on it.

**Comment by adrianschmidt** [comment]
This might be relevant: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute

**Comment by magnusfagerlund** [comment]
Is still a valid issue with the changes we've done in current cycle (cycle 13)?

**Comment by adrianschmidt** [comment]
> Is still a valid issue with the changes we've done in current cycle (cycle 13)?

I don't remember what changes were made in cycle 13, but the chipset still only shows the label if `type` is set to `input`. I can perhaps see some instances where you'd want to _not_ show a label for the other chipset types, but, firstly, those cases are when the chips are basically used as buttons rather than as inputs for data, and I'm not sure that's even a case where it would be a good idea to use a chipset. Secondly, it ought to be possible to simply not supply a label if none is to be shown.

So I think this should be done.

**Comment by adrianschmidt** [comment]
Ping @eketorp since I'm not sure if you're subscribed or not…

**Comment by eketorp** [comment]
Is it a coincidence that this one popped up? Sthlm team needs this feature. 
Personally, I think it's good to have the label optional. But apart from that, is there a lot to discuss related to the design? I guess fonts, sizes, padding, etc. is pretty set?
FYI: This is the application where we need labels. It should say Gungor, Klätterställning, Sandlåda as labels.
![image (3)](https://user-images.githubusercontent.com/58422324/106154722-2e929a80-6180-11eb-8017-77f01e1a3f26.png)

**Comment by eketorp** [comment]
@mjlime

**Comment by adrianschmidt** [comment]
No, not a coincidence… Mattias was asking about it in one of our Slack channels 😊

**Comment by adrianschmidt** [comment]
> is there a lot to discuss related to the design? I guess fonts, sizes, padding, etc. is pretty set?

I would assume it's pretty straightforward, yes. What do you say @Kiarokh?

**Comment by Kiarokh** [comment]
Oh I completely forgot that we had this already as an issue. Labels are great here for:

- They provide context for users with good sight (when needed, like in Tomas' example).
- They improve accessibility for users without sight (labels can be visually hidden by default, but they can still be used as `aria-describedby`, `aria-labelledby`, or `aria-label` to describe what a group of elements does. We who have good sight can sometimes make sense of the elements in the UI based on how the layout-design visually connects them to eacho ther. But blind users don't have this privilege.
- They can potentially make the layout better. Imagine the filter chipset or choice chipset being a part of a limel-form. It means they will be rendered beside all the other input fileds which have labels. It makes a lot of sense for them to have a label as well.

I'd say we definitely go for it. We should just make sure that the labels should look like other labels (when fields are focused [floating above effect from MD]), and have the same html structure. Something _similar_ tho below:

````html
<label 
    class="mdc-floating-label mdc-floating-label--float-above" 
    for="input-element">
    Text Field
</label>
’’’’

**Comment by Kiarokh** [comment]
So having a label would be obligatory or at least very highly recommended (given the accessibility requirements), but consumers should have a choice to visually display it or not. If they choose to hide it, we still output it as `aria-labelledby` in the dom. What do you say @adrianschmidt ?

**Comment by adrianschmidt** [comment]
I'm thinking that if the label isn't needed for sighted users, it probably isn't needed for accessibility either…?

I say, for now, we go with showing the label if there is one. If there isn't one, then we don't. That we, _if_ there's anyone out there currently using the chipset with any type other than `input`, they probably aren't supplying a label anyway, and then they keep getting the same thing they always did. I think it's doubtful that anyone is using the chipset like that, but if they are, they're probably using the one where `type` isn't set at all, and just using them as buttons because they like the look.
