### ISSUE TITLE
limel-select: There is no visual indication that the component is focused when tabbing to it

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#834]
## Current behavior

Focus a limel-select by tabbing to it.
There is no visual indication at all that the component is focused.
This means that the component is very hard to use by keyboard, despite it technically being fully accessible by keyboard.

## Expected behavior

There should be a clear visual indication that the component is focused.

## Environment

- **lime-elements** version: 26.31.1
- Framework used: reproducable in the docz-app
- Logs:

**Comment by adrianschmidt** [comment]
From a technical point of view, this should be very low-hanging fruit. I'm guessing it won't be very difficult for @Kiarokh to make the design either 🙂

**Comment by Kiarokh** [comment]
@adrianschmidt it's really hard to answer this question.

Well, first... bad old designer habits.... 
I have always completely ignored the fact that all components must be intractable with keyboard and this makes them more accessible. Because the inbuilt browser styles for `focus`, ir a very disgusting and freakingly shaped blue `outline` style, designers just carelessly have always done some `outline: none;` to "normalize" these visual styles. I've been one of them. 🙈😄

On the other hand, the problem with the `focus` state is that it is applied even if you are interacting with the mouse only (not keyboard). It would be nice to have a solution for only applying styles when keyboard navigation is detected. I think I've seen something like that on the web.
 
So in my head, I don't have a good series of visual solutions to indicate when components are "focused" with keyboard. Because I have always ignored this. I need to think about all types of elements in this case, to be able to give a rich and unified visual solution (buttons, radio buttons, links, table rows, pickers, menu items, etc...). That takes some time, but it's fully possible to do.

However, do we already have a solution for detecting keyboard navigation? So that I don't mess up the design for mouse users too?

**Comment by adrianschmidt** [comment]
> However, do we already have a solution for detecting keyboard navigation? So that I don't mess up the design for mouse users too?

We do in the webclient, but that just sets a class on the html element, and that obviously won't pierce shadow-doms, so won't affect components from lime-elements. I don't know if we can "reach out" to get hold of it in some way, like `html.show-focus-indicator :host {}` or something… (but even *if* that would work, I assume it wouldn't work for nested shadow-doms… 😬)

I guess we'll have to look into that.

In the meantime, maybe we could design an indicator that doesn't look horrid when used regardless of interaction method?

**Comment by adrianschmidt** [comment]
> This is when you start thinking, why aren't these things inbuilt in the browsers for god's sake after a century of internet? 😄

Yeah, I know…

> Yes we can design something decent. Let me think about this a little and I'll get back to you.

🙏 👍

**Comment by Kiarokh** [comment]
a question, should a `disabled` element (button, select, checkbox, etc...) still get focus with keyboard navigation? I have no idea how keyboard people expect them to react. 🤔

**Comment by Kiarokh** [comment]
@adrianschmidt I've done some fix, linked. It improves the focus state. 
However, it's not for `disabled` select. Not sure yet what's the standard there yet. 
Also the select behaves really strangely, and remains focused in many situations. For example when you click on the [disable] button below. Click around, inside and outside and check.

**Comment by adrianschmidt** [comment]
> a question, should a `disabled` element (button, select, checkbox, etc...) still get focus with keyboard navigation? I have no idea how keyboard people expect them to react. 🤔

Hmm… that's a *really* good question… 🤔

But no, for keyboard navigation only, I'd say you'd want to skip past any disabled options, since you can still see and read them. The question is how screen readers handle that. I mean, I think it's pretty widely agreed that disabled options should (usually) not be hidden from view, just clearly indicated as disabled. So it stands to reason that you'd want to get that information through a screen reader too, right? But maybe screen readers will take care of that themselves. Regardless, for now, I say we take them out of the tab flow. I'm pretty sure that's the default behaviour for native buttons and selects and stuff.

> Click around, inside and outside and check.

I'll take a look, probably Monday though 🙂

**Comment by Kiarokh** [comment]
> since you can still see and read them. 

Exactly, my assumption is also that the problem is those people who can't see or have poor eyesight. It's mainly them who use keyboard to navigate. So if they don't notice that there is an item that's disabled (such as a disabled save button), I guess they will never find it, thus never understand why they can't proceed.

I think we should sit down, do some research, and make a global solution for all of our interactive components and decide how focus should **work** and **appear** for each. As I said, my head is totally blank, when it comes to this keyboard navigation issue. 🙈 it's embarrassing 

But we can move forward with our current path anyway

**Comment by adrianschmidt** [comment]
> people who can't see or have poor eyesight. It's mainly them who use keyboard to navigate.

I'm not sure that's a valid assumption actually. It obviously depends a lot on both the user and the software, but especially for highly repetitive tasks, I think even fairly "standard" users will tend towards keyboard navigation.

But I completely agree that we should sit down and take an overall grip on this some time. Let's at the very least postpone the rest of this conversation until Monday, as I have some stuff to finish up before today's demo 🙂

**Comment by Kiarokh** [comment]
seems we had forgotten this poor issue and PR in the **triage** board :)

**Comment by Kiarokh** [comment]
a better solution here: https://github.com/Lundalogik/lime-elements/pull/1180 
I think I have found a way to handle these cases a bit more effectively :)
