### ISSUE TITLE
Missing label in limel-input-field type=textarea when prefilled text

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#950]
## Current behavior

See:

https://github.com/Lundalogik/lime-elements/issues/940 and https://github.com/Lundalogik/lime-elements/issues/722

Summarize, two bugs:
* Label is not visible when value is prefilled.
* When you remove all text, and blur the textarea, the last letter in the label disappears

I have created an add-on to reproduce this. Click on the button on the dashboard to open a dialog with a `limel-input-field` inside.

https://github.com/Lundalogik/limepkg-input-field-bug

Another note that I made: It works fine when you just put an input field on the dashboard. It don't work when you have the input field in a dialog (child-component?).

## Expected behavior

Visible label

## Environment

- **lime-elements** version: 28.0.1

**Comment by adrianschmidt** [comment]
Ping @sofiehelgesson: It seems this bug is back (you reported it in #940), or we didn't manage to reproduce it and thought it was fixed when it wasn't. I'm pinging you here so you can subscribe to this is issue if you wish.

**Comment by Kiarokh** [comment]
Is this helpful? https://github.com/material-components/material-components-web/issues/4439

**Comment by adrianschmidt** [comment]
> Is this helpful? [material-components/material-components-web#4439](https://github.com/material-components/material-components-web/issues/4439)

Hmm… it certainly looks like it might be related! We don't load the CSS separately though, I think… it ought to be included in the web component, so it ought to be applied already, and if it isn't I'm not sure there's much we can do about it. But it's certainly a very good lead to follow. Good find! 👍

**Comment by Kiarokh** [comment]
> When you remove all text, and blur the `textarea`, the last letter in the label disappears

![image](https://user-images.githubusercontent.com/35954987/100744689-798d6d00-33de-11eb-9074-b6b8791657d2.png)

As soon as the field gets `focus`, some code calculates an inline `width` and applies it to `<div class="mdc-notched-outline__notch">`. Then it recalculates the width, after you have typed something and clicked outside to remove the `focus`. I guess these issues are somehow related.

I'm experimenting with the "outlined" MD input fields now. It seems they are suffering the exact same problems. 
![noooo](https://user-images.githubusercontent.com/35954987/100745204-38e22380-33df-11eb-9fac-9a98ddd06479.gif)

**Comment by adrianschmidt** [comment]
Since the inputs in the gif above look normal outside of collapsible-sections, this is for sure caused by the inputs being hidden when they are created. They just need to be updated when the collapsible-section (or dialog) has opened. There are events sent from the respective components that can be hooked onto, and the input field has a `layout` method that can be called to make it adjust the dimensions and positions for all sub-elements. So this should be pretty easy to fix.

**Comment by Kiarokh** [comment]
![image](https://user-images.githubusercontent.com/35954987/101177926-a2189f80-3648-11eb-8905-669ae31f171b.png)
Labels seem to be empty sometimes, without being initially hidden under a section or similar. See the first field.

**Comment by adrianschmidt** [comment]
> ![image](https://user-images.githubusercontent.com/35954987/101177926-a2189f80-3648-11eb-8905-669ae31f171b.png)
> Labels seem to be empty sometimes, without being initially hidden under a section or similar. See the first field.

You frickin party-pooper :man-shaking-fist-in-air: <- that's clearly an emoji that needs to exist 😂

Seriously though, that's probably because of the limel-tabs. I don't think we emit a resize-event when switching tabs, and we'll need to do that. It should be a pretty simple fix 👍

**Comment by adrianschmidt** [comment]
> > Labels seem to be empty sometimes, without being initially hidden under a section or similar. See the first field.
> 
> You frickin party-pooper :man-shaking-fist-in-air: <- that's clearly an emoji that needs to exist 😂
> 
> Seriously though, that's probably because of the limel-tabs. I don't think we emit a resize-event when switching tabs, and we'll need to do that. It should be a pretty simple fix 👍
> 
> (I'll add a separate PR for that.)

I'm not able to reproduce this, and it seems the content of each tab would have to take care of it. Some tabs might show a loader when first revealed, so triggering a re-layout at that time wouldn't help anyway. The re-layout would have to be triggered once the tab has finished loading and the proper content is shown.

We can make sure we emit an event in from the proper component in lime-crm-components if this turns out to be a recurring problem, but I won't spend more time on it until we have determined that.
