### ISSUE TITLE
Export a mixins.scss that consumers can use

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#958]
## New feature motivation

There are some mixins that we use over and over, and it would be nice to be able to import those from a single source of truth, instead of having them duplicated over multiple repos.

## New feature description

Export a `mixins.scss` from lime-elements.

## New feature implementation

This file should not be importing any other scss files, and it should be exported as scss, not compiled to css.

**Comment by anderssonjohan** [comment]
In one of our packages we already use imports like this:

```scss
@use '../../../node_modules/@fullcalendar/timeline/main.min.css' as *;
@use '../../../node_modules/@fullcalendar/resource-timeline/main.min.css' as *;
@use '../../../node_modules/tippy.js/dist/tippy.css' as *;
```

This would of course be nice with lime-elements too, but they will very soon be out of date since this isn't updated when the lime-crm dependency updates.
When we build a package we compile the frontend using whatever lime-elements version that package has in its package.json, which may or may not be the same version that is used in the bundled app.

An invalid example but this:

`lwc-my-component.scss`
```
@use '../../../node_modules/lime-elements/dist/lime-elements.css' as *;

limel-button {
  @include is-flat-clickable;
}
```

...would use the `is-flat-clickable` mixin from the package' version of lime-elements, while the element `limel-button` comes from what's bundled with the app.

I still think this is a great idea but I wanted to bring this up if you haven't thought about it already.

**Comment by adrianschmidt** [comment]
> This would of course be nice with lime-elements too, but they will very soon be out of date since this isn't updated when the lime-crm dependency updates.

That's a good point, and I'm no longer so sure it's actually a good idea to export any sass mixins from lime-elements…

> An invalid example but this:
> 
> `lwc-my-component.scss`
> 
> ```css-scss
> @use '../../../node_modules/lime-elements/dist/lime-elements.css' as *;
> 
> limel-button {
>   @include is-flat-clickable;
> }
> ```
> 
> ...would use the `is-flat-clickable` mixin from the package' version of lime-elements, while the element `limel-button` comes from what's bundled with the app.

In cases like that, I think it's better that `is-flat-clickable` is just a property on the button, preferably with a better name.

**Comment by adrianschmidt** [comment]
I think the mixin we "use over and over", that I was thinking of when opening the issue, was `pxToRem`. I don't think it's worth putting in the effort to share such simple utility mixins between repos.

I'll close this issue, but feel free to convince me it should be opened again 😄
